version: '3.7'
services:
  demo-auth-db1:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=456123
      - MYSQL_DATABASE=demo
    volumes:
      - ./docker-volumes/demo-auth-db1/mysql:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"

  demo-auth1:
    image: demo-auth1:latest
    links:
      - demo-auth-db1:demo-auth-db1
    environment:
      - MYSQL_DB_USER=root
      - MYSQL_DB_PASSWORD=456123
      - MYSQL_DB_NAME=demo
      - MYSQL_DB_HOST=demo-auth-db1

  demo-rest1:
    image: demo-rest1:latest
    links:
      - demo-auth1:demo-auth1
    environment:
      - AUTH_MICROSERVICE_URL=http://demo-auth1
  lb:
    image: nginx:1.13-alpine
    ports:
      - 8181:80
    links:
      - demo-auth1
      - demo-rest1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
